version: '3'

services:
  postgres:
    image: postgres
    container_name: meu-postgres
    environment:
      POSTGRES_USER: admintcc
      POSTGRES_PASSWORD: Y79g7w8k4
      POSTGRES_DB: medcare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medcareapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
